// This file is auto-generated by @hey-api/openapi-ts

import { type Options, urlLinkGenerateCreate, urlLinkGenerateUpdate } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { UrlLinkGenerateCreateData, UrlLinkGenerateCreateResponse, UrlLinkGenerateUpdateData } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const urlLinkGenerateCreateQueryKey = (options?: Options<UrlLinkGenerateCreateData>) => createQueryKey('urlLinkGenerateCreate', options);

export const urlLinkGenerateCreateOptions = (options?: Options<UrlLinkGenerateCreateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await urlLinkGenerateCreate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: urlLinkGenerateCreateQueryKey(options)
    });
};

export const urlLinkGenerateCreateMutation = (options?: Partial<Options<UrlLinkGenerateCreateData>>): UseMutationOptions<UrlLinkGenerateCreateResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateCreateData>> => {
    const mutationOptions: UseMutationOptions<UrlLinkGenerateCreateResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await urlLinkGenerateCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const urlLinkGenerateUpdateMutation = (options?: Partial<Options<UrlLinkGenerateUpdateData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UrlLinkGenerateUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UrlLinkGenerateUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await urlLinkGenerateUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};