// This file is auto-generated by @hey-api/openapi-ts

import { type Options, urlLinkGenerateDestroy, urlLinkGenerateRetrieve, urlLinkGenerateCreate } from '../sdk.gen';
import { type UseMutationOptions, type DefaultError, queryOptions } from '@tanstack/react-query';
import type { UrlLinkGenerateDestroyData, UrlLinkGenerateDestroyResponse, UrlLinkGenerateRetrieveData, UrlLinkGenerateCreateData, UrlLinkGenerateCreateResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export const urlLinkGenerateDestroyMutation = (options?: Partial<Options<UrlLinkGenerateDestroyData>>): UseMutationOptions<UrlLinkGenerateDestroyResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateDestroyData>> => {
    const mutationOptions: UseMutationOptions<UrlLinkGenerateDestroyResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateDestroyData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await urlLinkGenerateDestroy({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const urlLinkGenerateRetrieveQueryKey = (options?: Options<UrlLinkGenerateRetrieveData>) => createQueryKey('urlLinkGenerateRetrieve', options);

export const urlLinkGenerateRetrieveOptions = (options?: Options<UrlLinkGenerateRetrieveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await urlLinkGenerateRetrieve({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: urlLinkGenerateRetrieveQueryKey(options)
    });
};

export const urlLinkGenerateCreateQueryKey = (options?: Options<UrlLinkGenerateCreateData>) => createQueryKey('urlLinkGenerateCreate', options);

export const urlLinkGenerateCreateOptions = (options?: Options<UrlLinkGenerateCreateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await urlLinkGenerateCreate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: urlLinkGenerateCreateQueryKey(options)
    });
};

export const urlLinkGenerateCreateMutation = (options?: Partial<Options<UrlLinkGenerateCreateData>>): UseMutationOptions<UrlLinkGenerateCreateResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateCreateData>> => {
    const mutationOptions: UseMutationOptions<UrlLinkGenerateCreateResponse, AxiosError<DefaultError>, Options<UrlLinkGenerateCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await urlLinkGenerateCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};