// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ManagerLoginDestroyData, ManagerLoginDestroyResponses, ManagerLoginRetrieveData, ManagerLoginRetrieveResponses, ManagerLoginCreateData, ManagerLoginCreateResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const managerLoginDestroy = <ThrowOnError extends boolean = false>(options?: Options<ManagerLoginDestroyData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<ManagerLoginDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/manager/login/',
        ...options
    });
};

export const managerLoginRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ManagerLoginRetrieveData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ManagerLoginRetrieveResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/manager/login/',
        ...options
    });
};

export const managerLoginCreate = <ThrowOnError extends boolean = false>(options: Options<ManagerLoginCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ManagerLoginCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            }
        ],
        url: '/manager/login/',
        ...options
    });
};