// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { UrlAcknowledgmentUpdateData, UrlAcknowledgmentUpdateResponses, UrlLinkGenerateDestroyData, UrlLinkGenerateDestroyResponses, UrlLinkGenerateListData, UrlLinkGenerateListResponses, UrlLinkGenerateCreateData, UrlLinkGenerateCreateResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const urlAcknowledgmentUpdate = <ThrowOnError extends boolean = false>(options: Options<UrlAcknowledgmentUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UrlAcknowledgmentUpdateResponses, unknown, ThrowOnError>({
        url: '/url/acknowledgment/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const urlLinkGenerateDestroy = <ThrowOnError extends boolean = false>(options?: Options<UrlLinkGenerateDestroyData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<UrlLinkGenerateDestroyResponses, unknown, ThrowOnError>({
        url: '/url/link-generate/',
        ...options
    });
};

export const urlLinkGenerateList = <ThrowOnError extends boolean = false>(options?: Options<UrlLinkGenerateListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UrlLinkGenerateListResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/url/link-generate/',
        ...options
    });
};

export const urlLinkGenerateCreate = <ThrowOnError extends boolean = false>(options?: Options<UrlLinkGenerateCreateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<UrlLinkGenerateCreateResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/url/link-generate/',
        ...options
    });
};