// This file is auto-generated by @hey-api/openapi-ts

export type Device = {
    readonly id: number;
    readonly user_location: string;
    ip_address: string;
    location?: string | null;
    device_det: string;
    readonly last_active: string;
    readonly last_login: string;
    is_active?: boolean;
    is_flagged?: boolean;
};

export type Login = {
    first_name: string;
    last_name: string;
    email: string;
};

export type LoginActivityError = {
    readonly msg: string;
};

export type LoginActivityPut = {
    readonly msg: string;
};

export type LoginActivityRequest = {
    is_flagged: boolean;
    id: number;
};

export type LoginActivitySessionError = {
    readonly msg: string;
};

export type LoginRequest = {
    longitude: number;
    latitude: number;
};

export type ManagerActivityRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manager/activity/';
};

export type ManagerActivityRetrieveResponses = {
    200: Device;
};

export type ManagerActivityRetrieveResponse = ManagerActivityRetrieveResponses[keyof ManagerActivityRetrieveResponses];

export type ManagerActivityUpdateData = {
    body: LoginActivityRequest;
    path?: never;
    query?: never;
    url: '/manager/activity/';
};

export type ManagerActivityUpdateErrors = {
    400: LoginActivityError;
    409: LoginActivitySessionError;
};

export type ManagerActivityUpdateError = ManagerActivityUpdateErrors[keyof ManagerActivityUpdateErrors];

export type ManagerActivityUpdateResponses = {
    200: LoginActivityPut;
};

export type ManagerActivityUpdateResponse = ManagerActivityUpdateResponses[keyof ManagerActivityUpdateResponses];

export type ManagerLoginDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manager/login/';
};

export type ManagerLoginDestroyResponses = {
    /**
     * Unspecified response body
     */
    200: {
        [key: string]: unknown;
    };
};

export type ManagerLoginDestroyResponse = ManagerLoginDestroyResponses[keyof ManagerLoginDestroyResponses];

export type ManagerLoginRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manager/login/';
};

export type ManagerLoginRetrieveResponses = {
    200: Login;
};

export type ManagerLoginRetrieveResponse = ManagerLoginRetrieveResponses[keyof ManagerLoginRetrieveResponses];

export type ManagerLoginCreateData = {
    body: LoginRequest;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/manager/login/';
};

export type ManagerLoginCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://100.74.154.19:8001' | (string & {});
};