// This file is auto-generated by @hey-api/openapi-ts

export type AcknowledgementRequest = {
    acknowledgement: boolean;
    uuid: string;
};

export type GetUrl = {
    Url: string;
    Key: string;
};

export type Url = {
    url: string;
    readonly uuid: string;
};

export type UrlAcknowledgmentUpdateData = {
    body: AcknowledgementRequest;
    path?: never;
    query?: never;
    url: '/url/acknowledgment/';
};

export type UrlAcknowledgmentUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UrlLinkGenerateDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/url/link-generate/';
};

export type UrlLinkGenerateDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UrlLinkGenerateDestroyResponse = UrlLinkGenerateDestroyResponses[keyof UrlLinkGenerateDestroyResponses];

export type UrlLinkGenerateListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/url/link-generate/';
};

export type UrlLinkGenerateListResponses = {
    200: Array<GetUrl>;
};

export type UrlLinkGenerateListResponse = UrlLinkGenerateListResponses[keyof UrlLinkGenerateListResponses];

export type UrlLinkGenerateCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/url/link-generate/';
};

export type UrlLinkGenerateCreateResponses = {
    200: Url;
};

export type UrlLinkGenerateCreateResponse = UrlLinkGenerateCreateResponses[keyof UrlLinkGenerateCreateResponses];

export type ClientOptions = {
    baseURL: 'http://100.74.154.19:8001' | (string & {});
};