// This file is auto-generated by @hey-api/openapi-ts

export type Url = {
    url: string;
    readonly uuid: string;
};

export type UrlLinkGenerateCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/url/link-generate/';
};

export type UrlLinkGenerateCreateResponses = {
    200: Url;
};

export type UrlLinkGenerateCreateResponse = UrlLinkGenerateCreateResponses[keyof UrlLinkGenerateCreateResponses];

export type UrlLinkGenerateUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/url/link-generate/';
};

export type UrlLinkGenerateUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://10.21.98.201:8000' | (string & {});
};